In [3]:
import numpy as np
import pandas as pd

In [9]:
#1 create empty and full numpy arrays

arr1=np.empty(10)
arr1
arr2=np.full(10,2) #creates an array of 10 with 2 values
arr2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
#2 Create array with all zeroes and one's
arr1=np.zeros(10)
arr1
arr2=np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#3 Check if specified row is present in array

arr=np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])

for row in arr.tolist():
    if([1,2,3]== row):
        print(row)

[1, 2, 3]


In [24]:
#4 Combine a 1d and 2d NP array

arr=np.arange(5)
print(arr)
arr2=np.arange(10).reshape(2,5)
print(arr2)
for a,b in np.nditer([arr, arr2]):
    print(a,b)


[0 1 2 3 4]
[[0 1 2 3 4]
 [5 6 7 8 9]]
0 0
1 1
2 2
3 3
4 4
0 5
1 6
2 7
3 8
4 9


In [42]:
#5 checking for equal, greater or lesser arrays
# a=np.arange(0,10,2)
# b=np.arange(0,20,3) 
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

np.greater(a,b)
np.less(a,b)
np.array_equal(a,b)

False

In [50]:
#6 Getting 2d diagonals from 3d arrays
arr_3=np.arange(3*4*4).reshape(3,4,4)
print(arr_3)
np.diagonal(arr_3,0,0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 0, 20, 40],
       [ 1, 21, 41],
       [ 2, 22, 42],
       [ 3, 23, 43]])

In [61]:
#7 Flattening array to 1d 
arr=np.arange(0,10).reshape(2,5)
arr.flatten(order='A') #order F for column wise and order C for row wise


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
#Reverse using NumPy
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr=np.arange(0,10).reshape(2,5)
arr.max()
arr.min()
arr.sum()

arr+arr
arr*arr
arr-arr
arr.shape

np.concatenate([arr,np.array(['a','b'])],axis=0)

[ 1  2  3  4  5  6  7  8  9 10]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [95]:
#Eigen Values
from numpy import linalg as la
arr=np.arange(1,10).reshape(3,3)
la.eigvals(arr)
#Frequency of Unique Values
np.unique(arr)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
#Make a pandas DataFrame using list
list=[['Geek', 25], ['is', 30], 
       ['for', 26], ['Geeksforgeeks', 22]] 
df=pd.DataFrame(list,columns=['Tag','Number'])
df
dict={'Name':['Rayan','Wahid','Bhat'],
     'Roll No':[35,36,37]}
df1=pd.DataFrame(dict)
df1

Name  Roll No
0  Rayan       35
1  Wahid       36
2   Bhat       37

In [ ]:
# df['Col1'].apply(function name)
# This is used to apply a function to a column